-t option now stops without building source package

diff --git a/scripts/buildeb b/scripts/buildeb
--- a/scripts/buildeb
+++ b/scripts/buildeb
@@ -811,17 +811,18 @@ env echo -e "\t\n" >> debian/rules
 #created a script called _correct\_lintian.pl_, that corrects some of thoses
 #errors. 
 
-echo "Building source package..." | tee -a $LOGFILE $FULLLOGFILE
-debuild -S -uc -us | log
-if [ ${PIPESTATUS[0]} -ne 0 ]; then
-    echo "Source package building failed." | tee -a $LOGFILE $FULLLOGFILE
-    exit 12
-fi
-echo "Source package successfully built." | tee -a $LOGFILE $FULLLOGFILE
+if [ $quitbeforebuild -eq 0 ]; then
+    echo "Building source package..." | tee -a $LOGFILE $FULLLOGFILE
+    debuild -S -uc -us | log
+    if [ ${PIPESTATUS[0]} -ne 0 ]; then
+        echo "Source package building failed." | tee -a $LOGFILE $FULLLOGFILE
+        exit 12
+    fi
+    echo "Source package successfully built." | tee -a $LOGFILE $FULLLOGFILE
 
-echo "Running correction to lintian errors..." | tee -a $LOGFILE $FULLLOGFILE
-$LINTIAN "$MAKEFILEDIR/../$PACKNAME""-1_source.build" | log
-echo "Lintian errors corrected." | tee -a $LOGFILE $FULLLOGFILE
+    echo "Running correction to lintian errors..." | tee -a $LOGFILE $FULLLOGFILE
+    $LINTIAN "$MAKEFILEDIR/../$PACKNAME""-1_source.build" | log
+    echo "Lintian errors corrected." | tee -a $LOGFILE $FULLLOGFILE
    
 #<a id='libbuild'>Building the package</a>
 #-----------------------------------------
@@ -829,19 +830,15 @@ echo "Lintian errors corrected." | tee -a $LOGFILE $FULLLOGFILE
 #Now, we can finally build the package. _debuild_ does pretty much all the work.
 #-us and -uc options means that we don't sign the packages.
 
-rm -f "../$LIBPACKAGENAME""_$VERSION-1.debian.tar.gz" | log
-rm -f "../$BINPACKAGENAME""_$VERSION-1.debian.tar.gz" | log
-rm -f "../$INDPACKAGENAME""_$VERSION-1.debian.tar.gz" | log
-rm -f ../*.build ../*.changes | log
-if [ $quitbeforebuild -eq 1 ]; then
-    rm -f ../*.debian.tar.gz | log
-    rm -f ../*.dsc | log
-else
+    rm -f "../$LIBPACKAGENAME""_$VERSION-1.debian.tar.gz" | log
+    rm -f "../$BINPACKAGENAME""_$VERSION-1.debian.tar.gz" | log
+    rm -f "../$INDPACKAGENAME""_$VERSION-1.debian.tar.gz" | log
+    rm -f ../*.build ../*.changes | log
     echo "Building debian packages..." | tee -a $LOGFILE $FULLLOGFILE
     debuild -us -uc | log
     if [ ${PIPESTATUS[0]} -ne 0 ]; then
-	echo "Package building failed." | tee -a $LOGFILE $FULLLOGFILE
-	exit 13
+        echo "Package building failed." | tee -a $LOGFILE $FULLLOGFILE
+        exit 13
     fi
     echo "Debian packages successfully built." | tee -a $LOGFILE $FULLLOGFILE
 fi
@@ -849,12 +846,9 @@ fi
 #We now have to remove the debian directory, the tarballs, and some files
 #created by _debuild_.
 
-if [ $leaveunclean -eq 0 ]
-then
+if [ $leaveunclean -eq 0 ]; then
     echo "Cleaning directory..." | tee -a $LOGFILE $FULLLOGFILE
-    if [ $quitbeforebuild -ne 1 ]; then
-	rm -rf debian/ | log
-    fi
+    rm -rf debian/ | log
     cd $MAKEFILEDIR/.. | log
     rm -f "$TARBALL" | log
     rm -f "$LIBPACKAGENAME""_$VERSION-1.debian.tar.gz" | log
