Corrected verbose mode to work correctly

diff --git a/scripts/buildeb b/scripts/buildeb
--- a/scripts/buildeb
+++ b/scripts/buildeb
@@ -287,22 +287,23 @@ fi
 #<a id='log'>Creating log</a>
 #----------------------------
 
-#We create a log file to keep track of what has been done and we redirect
-#standard output to another log to keep the console clean and readable.
+#We create a log file to keep track of what has been done and we define a 
+#function to have a log with a verbose mode.
 
 LOGDIR=`readlink -f $MAKEFILEDIR/..`
 LOGFILE=$LOGDIR/buildeb.log
 FULLLOGFILE=$LOGDIR/buildeb_full.log
-echo LOGDIR = $LOGDIR
 
 :> $LOGFILE
 :> $FULLLOGFILE
 
-if [ $verbosemode -eq 1 ]; then
-    VERBOSE="tee -a $LOGFILE $FULLLOGFILE"
-else
-    VERBOSE="tee -a >> $LOGFILE $FULLLOGFILE"
-fi
+log() {
+    if [[ $verbosemode -eq 1 ]]; then
+	tee -a $FULLLOGFILE
+    else
+	cat >> $FULLLOGFILE
+    fi
+}
 
 env echo -e "This log was generated by buildeb while building a \n\
 debian package from the sources in $MAKEFILEDIR.\n" | tee -a $LOGFILE \
@@ -320,9 +321,9 @@ env echo -e "Timestamp :     $timestamp\n" | tee -a $LOGFILE $FULLLOGFILE
 if [ -z "$VERSION" ]; then
     echo "Version not specified. We will use the current timestamp." | \
 	tee -a $LOGFILE $FULLLOGFILE
-    echo "date +%s" | ${VERBOSE}
+    echo "date +%s" | log
     VERSION=`date +%s`
-    echo $VERSION | ${VERBOSE}
+    echo $VERSION | log
 fi
 
 echo "Executing before build commands..." | tee -a $LOGFILE $FULLLOGFILE
@@ -331,7 +332,7 @@ IFS=';' read -a commands <<< "$BEFOREBUILD"
 for cmd in "${commands[@]}"
 do
     echo $cmd | tee -a $LOGFILE $FULLLOGFILE
-    eval "$cmd"
+    eval "$cmd" | log
 done
 echo "Before build commands executed..." | tee -a $LOGFILE $FULLLOGFILE
 
@@ -387,9 +388,9 @@ then
     TARBALL="$INDPACKAGENAME""_$VERSION.orig.tar.gz"
     PACKNAME="$INDPACKAGENAME""_$VERSION"
 fi
-echo "tar czf "../$TARBALL" ." | ${VERBOSE}
-tar czf "../$TARBALL" . | ${VERBOSE}
-echo "Tarball $TARBALL created." | tee -a $LOGFILE $FULLLOGFILE
+echo "tar czf "../$TARBALL" ." | log
+tar czf "../$TARBALL" . | log
+echo "Tarball $TARBALL created." | log
     
 
 #<a id='copyright'>The copyright file</a>
@@ -463,8 +464,8 @@ echo "Creation of debian files" | tee -a $LOGFILE $FULLLOGFILE
 #First we have to remove the debian directory, because if there is one,
 #dh_make will not make any changes, and that's not what we want.
 
-echo "rm -rf debian/" | ${VERBOSE}
-rm -rf debian/
+echo "rm -rf debian/" | log
+rm -rf debian/ | log
 
 #We create a temporary file that only contains a blank line. We do that because
 #dh_make waits an input from the user. We know that there's a -y option that
@@ -484,19 +485,19 @@ copy="-c $COPYRIGHT"
 fi
 if [ $LIBPACK == true ]
 then
-    echo "dh_make -l $copy -p $PACKNAME" | ${VERBOSE}
-    dh_make -l $copy -p $PACKNAME < debtmpfile | ${VERBOSE}
+    echo "dh_make -l $copy -p $PACKNAME" | log
+    dh_make -l $copy -p $PACKNAME < debtmpfile | log
 elif [ $BINPACK == true ]
 then
-    echo "dh_make -s $copy -p $PACKNAME" | ${VERBOSE}
-    dh_make -s $copy -p $PACKNAME < debtmpfile | ${VERBOSE}
+    echo "dh_make -s $copy -p $PACKNAME" | log
+    dh_make -s $copy -p $PACKNAME < debtmpfile | log
 elif [ $INDPACK == true ]
 then
-    echo "dh_make -i $copy -p $PACKNAME" | ${VERBOSE}
-    dh_make -i $copy -p $PACKNAME < debtmpfile | ${VERBOSE}
+    echo "dh_make -i $copy -p $PACKNAME" | log
+    dh_make -i $copy -p $PACKNAME < debtmpfile | log
 fi
 if [ $? -ne 0 ]; then
-    echo "dh_make failed. Check your version number and your package name";
+    echo "dh_make failed. Check your version number and your package name" >&2
     exit 7
 fi
 
@@ -504,14 +505,14 @@ fi
 
 if [ "$COPYRIGHTTYPE" = "file" ] 
 then
-    echo "cp $COPYRIGHT debian/copyright" | ${VERBOSE}
-    cp $COPYRIGHT debian/copyright
+    echo "cp $COPYRIGHT debian/copyright" | log
+    cp $COPYRIGHT debian/copyright | log
 fi
 
 #We then remove the temporary file we have created.
 
-echo "rm -f debtmpfile" | ${VERBOSE}
-rm -f debtmpfile
+echo "rm -f debtmpfile" | log
+rm -f debtmpfile | log
 
 echo "Template files generated by dh_make." | tee -a $LOGFILE $FULLLOGFILE
 
@@ -520,21 +521,12 @@ echo "Template files generated by dh_make." | tee -a $LOGFILE $FULLLOGFILE
 
 #dh\_make creates the debian directory, and all the files in it. Therefore, we
 #must modify some of them, because some of them are not complete.
-
-#First, we need to modify the changelog file, because if we don't, the name
-#of the package will be something like : `<packagename>_<version>-1_<archi>.deb`
-#. This is not what we want. We want something like :
-#`<packagename>_<version>_<archi>.deb`.
-
-#echo "perl -pi -e 's/\(((\d+\.?)+)-\d+\)/($1)/' debian/changelog" >>\
-# $FULLLOGFILE
-#perl -pi -e 's/\(((\d+\.?)+)-\d+\)/($1)/' debian/changelog
     
 #Some of the files generated by dh_make are just examples of what you should 
 #provide. This is not interesting to us, therefore we have to suppress them.
 
-echo "rm -rf debian/*.EX debian/*.ex debian/README*" | ${VERBOSE}
-rm -rf debian/*.EX debian/*.ex debian/README*
+echo "rm -rf debian/*.EX debian/*.ex debian/README*" | log
+rm -rf debian/*.EX debian/*.ex debian/README* | log
 
 #We then have to rename the dirs files and the install files that have been
 #created by dh\_make. .dirs files tells _debuild_ what are the directories
@@ -550,12 +542,11 @@ rm -rf debian/*.EX debian/*.ex debian/README*
 
 if [ $LIBPACK == true ]
 then
-    echo "mv debian/$LIBPACKAGENAME""1.dirs" debian/$LIBPACKAGENAME.dirs >> \
-$FULLLOGFILE
-    mv debian/"$LIBPACKAGENAME"1.dirs debian/"$LIBPACKAGENAME".dirs
-    echo "mv debian/$LIBPACKAGENAME""1.install" debian/$LIBPACKAGENAME.install \
-| ${VERBOSE}
-    mv debian/"$LIBPACKAGENAME"1.install debian/"$LIBPACKAGENAME".install
+    echo "mv debian/$LIBPACKAGENAME""1.dirs" debian/$LIBPACKAGENAME.dirs | log
+    mv debian/"$LIBPACKAGENAME"1.dirs debian/"$LIBPACKAGENAME".dirs | log
+    echo "mv debian/$LIBPACKAGENAME""1.install" debian/$LIBPACKAGENAME.install\
+ | log
+    mv debian/"$LIBPACKAGENAME"1.install debian/"$LIBPACKAGENAME".install | log
 fi
 
 #If we're building library packages, we must modify the control file because
@@ -566,8 +557,9 @@ fi
 if [ $LIBPACK == true ]
 then
     echo "sed -i -r -e s/$LIBPACKAGENAME""BROKEN/$LIBPACKAGENAME/g \
- debian/control" | ${VERBOSE}
-    sed -i -r -e s/"$LIBPACKAGENAME"BROKEN/"$LIBPACKAGENAME"/g debian/control
+ debian/control" | log
+    sed -i -r -e s/"$LIBPACKAGENAME"BROKEN/"$LIBPACKAGENAME"/g debian/control\
+ | log
     echo "Library package renamed to $LIBPACKAGENAME." | tee -a $LOGFILE \
 	$FULLLOGFILE
 fi
@@ -588,8 +580,8 @@ then
 #Libraries will be put in `/usr/lib/LIBPACKAGENAME/` when the package is 
 #installed
     
-    echo "rm -f debian/$LIBPACKAGENAME.install" | ${VERBOSE}
-    rm -f debian/$LIBPACKAGENAME.install
+    echo "rm -f debian/$LIBPACKAGENAME.install" | log
+    rm -f debian/$LIBPACKAGENAME.install | log
     for library in $LIBNAMES
     do
 	echo "$library usr/lib/$LIBPACKAGENAME" >>debian/$LIBPACKAGENAME.install
@@ -607,7 +599,8 @@ debian/$LIBPACKAGENAME.install : $LIBNAMES." | tee -a $LOGFILE $FULLLOGFILE
 
     if [ ! -z "$HEADERNAMES" ]
     then
-	rm -f debian/$LIBPACKAGENAME-dev.install;
+	echo "rm -f debian/$LIBPACKAGENAME-dev.install" | log
+	rm -f debian/$LIBPACKAGENAME-dev.install | log
 	for header in $HEADERNAMES
 	do
 	    echo "$header usr/include/$LIBPACKAGENAME" >>\
@@ -619,7 +612,7 @@ debian/$LIBPACKAGENAME-dev.install : $HEADERNAMES." | tee -a $LOGFILE \
 	    $FULLLOGFILE
     else
 	perl -0777 -pi -e "s/Package: $LIBPACKAGENAME-dev.+?\n\n//s" \
-	    debian/control
+	    debian/control | log
     fi
 fi
 
@@ -716,8 +709,8 @@ fi
 if [ ! -z "$BINRUNDEPENDS" ]
 then
     echo "perl -0777 -pi -e 's/(Package: $BINPACKAGENAME.*?Depends:.+?)\n/$1, \
-$BINRUNDEPENDS/s' debian/control" | ${VERBOSE}
-    perl -0777 -pi -e 's/(Package: '"$BINPACKAGENAME"'.*?Depends:.+?)\n/$1, '"$BINRUNDEPENDS\n/s" debian/control 
+$BINRUNDEPENDS/s' debian/control" | log
+    perl -0777 -pi -e 's/(Package: '"$BINPACKAGENAME"'.*?Depends:.+?)\n/$1, '"$BINRUNDEPENDS\n/s" debian/control  | log
     echo "Added binaries' runtime dependencies to debian/control :\
  $BINRUNDEPENDS." | tee -a $LOGFILE $FULLLOGFILE
 fi
@@ -725,8 +718,8 @@ fi
 if [ ! -z "$LIBRUNDEPENDS" ]
 then
     echo "perl -0777 -pi -e 's/(Package: $LIBPACKAGENAME.*?Depends:.+?)\n/$1, \
-$LIBRUNDEPENDS/s' debian/control" | ${VERBOSE}
-    perl -0777 -pi -e 's/(Package: '"$LIBPACKAGENAME"'.*?Depends:.+?)\n/$1, '"$LIBRUNDEPENDS\n/s" debian/control 
+$LIBRUNDEPENDS/s' debian/control" | log
+    perl -0777 -pi -e 's/(Package: '"$LIBPACKAGENAME"'.*?Depends:.+?)\n/$1, '"$LIBRUNDEPENDS\n/s" debian/control  | log
     echo "Added libraries' runtime dependencies to debian/control :\
  $LIBRUNDEPENDS." | tee -a $LOGFILE $FULLLOGFILE
 fi
@@ -734,8 +727,8 @@ fi
 if [ ! -z "$INDRUNDEPENDS" ]
 then
     echo "perl -0777 -pi -e 's/(Package: $INDPACKAGENAME.*?Depends:.+?)\n/$1, \
-$INDRUNDEPENDS/s' debian/control" | ${VERBOSE}
-    perl -0777 -pi -e 's/(Package: '"$INDPACKAGENAME"'.*?Depends:.+?)\n/$1, '"$INDRUNDEPENDS\n/s" debian/control 
+$INDRUNDEPENDS/s' debian/control" | log
+    perl -0777 -pi -e 's/(Package: '"$INDPACKAGENAME"'.*?Depends:.+?)\n/$1, '"$INDRUNDEPENDS\n/s" debian/control  | log
     echo "Added arch-independant files' runtime dependencies to debian/control :\
 $INDRUNDEPENDS." | tee -a $LOGFILE $FULLLOGFILE
 fi
@@ -743,8 +736,9 @@ fi
 if [ ! -z "$BUILDDEPENDS" ]
 then
     echo "perl -pi -e 's/(Build-Depends:.+)$/$1, $BUILDDEPENDS/' debian/control"\
-| ${VERBOSE}
-    perl -pi -e 's/(Build-Depends:.+)$/$1, '"$BUILDDEPENDS/" debian/control
+ | log
+    perl -pi -e 's/(Build-Depends:.+)$/$1, '"$BUILDDEPENDS/" debian/control\
+ | log
     echo "Added build dependencies to debian/control : $BUILDDEPENDS." \
 	| tee -a $LOGFILE $FULLLOGFILE
 fi
@@ -802,8 +796,8 @@ env echo -e "\t\n" >> debian/rules
 #errors. 
 
 echo "Building source package..." | tee -a $LOGFILE $FULLLOGFILE
-echo "debuild -S -uc -us" | ${VERBOSE}
-debuild -S -uc -us | ${VERBOSE}
+echo "debuild -S -uc -us" | log
+debuild -S -uc -us | log
 
 if [ $? -ne 0 ]; then
     echo "Source package building failed." | tee -a $LOGFILE $FULLLOGFILE
@@ -812,8 +806,8 @@ fi
 echo "Source package successfully built." | tee -a $LOGFILE $FULLLOGFILE
 
 echo "Running correction to lintian errors..." | tee -a $LOGFILE $FULLLOGFILE
-echo "$LINTIAN $MAKEFILEDIR/../$PACKNAME""-1_source.build" | ${VERBOSE}
-$LINTIAN "$MAKEFILEDIR/../$PACKNAME""-1_source.build" | ${VERBOSE}
+echo "$LINTIAN $MAKEFILEDIR/../$PACKNAME""-1_source.build" | log
+$LINTIAN "$MAKEFILEDIR/../$PACKNAME""-1_source.build" | log
 echo "Lintian errors corrected." | tee -a $LOGFILE $FULLLOGFILE
    
 #<a id='libbuild'>Building the package</a>
@@ -822,27 +816,23 @@ echo "Lintian errors corrected." | tee -a $LOGFILE $FULLLOGFILE
 #Now, we can finally build the package. _debuild_ does pretty much all the work.
 #-us and -uc options means that we don't sign the packages.
 
-echo "rm -f ../$LIBPACKAGENAME""_$VERSION.debian.tar.gz" | ${VERBOSE}
-rm -f "../$LIBPACKAGENAME""_$VERSION.debian.tar.gz"
-echo "rm -f ../$BINPACKAGENAME""_$VERSION.debian.tar.gz" | ${VERBOSE}
-rm -f "../$BINPACKAGENAME""_$VERSION.debian.tar.gz"
-echo "rm -f ../$INDPACKAGENAME""_$VERSION.debian.tar.gz" | ${VERBOSE}
-rm -f "../$INDPACKAGENAME""_$VERSION.debian.tar.gz"
-echo "rm -f ../*.build ../*.changes" | ${VERBOSE}
-rm -f ../*.build ../*.changes
+echo "rm -f ../$LIBPACKAGENAME""_$VERSION.debian.tar.gz" | log
+rm -f "../$LIBPACKAGENAME""_$VERSION.debian.tar.gz" | log
+echo "rm -f ../$BINPACKAGENAME""_$VERSION.debian.tar.gz" | log
+rm -f "../$BINPACKAGENAME""_$VERSION.debian.tar.gz" | log
+echo "rm -f ../$INDPACKAGENAME""_$VERSION.debian.tar.gz" | log
+rm -f "../$INDPACKAGENAME""_$VERSION.debian.tar.gz" | log
+echo "rm -f ../*.build ../*.changes" | log
+rm -f ../*.build ../*.changes | log
 if [ $quitbeforebuild -eq 1 ]; then
-    echo "rm -f ../*.debian.tar.gz" | ${VERBOSE}
-    rm -f ../*.debian.tar.gz
-    echo "rm -f ../*.dsc" | ${VERBOSE}
-    rm -f ../*.dsc
-    echo "You can now edit the configuration files located in \
-$MAKEFILEDIR/debian and build your packages using 'debuild'. Check debuild's \
-manpage for more information." | tee -a $LOGFILE $FULLLOGFILE
-
+    echo "rm -f ../*.debian.tar.gz" | log
+    rm -f ../*.debian.tar.gz | log
+    echo "rm -f ../*.dsc" | log
+    rm -f ../*.dsc | log
 else
     echo "Building debian packages..." | tee -a $LOGFILE $FULLLOGFILE
-    echo "debuild -us -uc" | ${VERBOSE}
-    debuild -us -uc | ${VERBOSE}
+    echo "debuild -us -uc" | log
+    debuild -us -uc | log
     if [ $? -ne 0 ]; then
 	echo "Package building failed." | tee -a $LOGFILE $FULLLOGFILE
 	exit 6
@@ -857,21 +847,21 @@ if [ $leaveunclean -eq 0 ]
 then
     echo "Cleaning directory..." | tee -a $LOGFILE $FULLLOGFILE
     if [ $quitbeforebuild -ne 1 ]; then
-	echo "rm -rf debian/ && cd .." | ${VERBOSE}
-	rm -rf debian/
+	echo "rm -rf debian/ && cd .." | log
+	rm -rf debian/ | log
     fi
-    echo "cd `readlink -f $MAKEFILEDIR/..`" | ${VERBOSE}
-    cd $MAKEFILEDIR/..
-    echo "rm -f $TARBALL"  | ${VERBOSE}
-    rm -f "$TARBALL"
-    echo "rm -f $LIBPACKAGENAME""_$VERSION.debian.tar.gz" | ${VERBOSE}
-    rm -f "$LIBPACKAGENAME""_$VERSION.debian.tar.gz"
-    echo "rm -f $BINPACKAGENAME""_$VERSION.debian.tar.gz" | ${VERBOSE}
-    rm -f "$BINPACKAGENAME""_$VERSION.debian.tar.gz"
-    echo "rm -f $INDPACKAGENAME""_$VERSION.debian.tar.gz" | ${VERBOSE}
-    rm -f "$INDPACKAGENAME""_$VERSION.debian.tar.gz"
-    echo "rm -f *.build *.changes" | ${VERBOSE}
-    rm -f *.build *.changes
+    echo "cd `readlink -f $MAKEFILEDIR/..`" | log
+    cd $MAKEFILEDIR/.. | log
+    echo "rm -f $TARBALL" | log
+    rm -f "$TARBALL" | log
+    echo "rm -f $LIBPACKAGENAME""_$VERSION.debian.tar.gz" | log
+    rm -f "$LIBPACKAGENAME""_$VERSION.debian.tar.gz" | log
+    echo "rm -f $BINPACKAGENAME""_$VERSION.debian.tar.gz" | log
+    rm -f "$BINPACKAGENAME""_$VERSION.debian.tar.gz" | log
+    echo "rm -f $INDPACKAGENAME""_$VERSION.debian.tar.gz" | log
+    rm -f "$INDPACKAGENAME""_$VERSION.debian.tar.gz" | log
+    echo "rm -f *.build *.changes" | log
+    rm -f *.build *.changes | log
 fi
     
 #<a id='afterbuild'>Running After build operations</a>
@@ -879,18 +869,27 @@ fi
 
 #We execute commands specified in the configuration file in the field AFTERBUILD
 
-cd $MAKEFILEDIR
+echo "cd $MAKEFILEDIR" | log
+cd $MAKEFILEDIR | log
 echo "Executing after build commands..." | tee -a $LOGFILE $FULLLOGFILE
 IFS=';' read -a commands <<< "$AFTERBUILD"
 for cmd in "${commands[@]}"
 do
     echo $cmd | tee -a $LOGFILE $FULLLOGFILE
-    eval "$cmd"
+    eval "$cmd" | log
 done
 
 echo "After build commands executed." | tee -a $LOGFILE $FULLLOGFILE
 
-env echo -e "\nYou can now find your debian packages and logs in $LOGDIR. \
+
+if [ $quitbeforebuild -eq 1 ]; then
+    echo "You can now edit the configuration files located in \
+$MAKEFILEDIR/debian and build your packages using 'debuild'. Check debuild's \
+manpage for more information." | tee -a $LOGFILE $FULLLOGFILE
+else
+    env echo -e "\nYou can now find your debian packages and logs in $LOGDIR. \
 buildeb.log is the same as the previous output, and buildeb_full.log is a \
 complete output of every program called by buildeb (compilation, package \
 building operations, etc...)." | tee -a $LOGFILE $FULLLOGFILE
+fi
+
